# This is a basic workflow to help you get started with Actions

name: CI - test BioImage.IO resources with DeepImageJ

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab (github website)
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Check out another repository
      - uses: actions/checkout@v3
        with:
          repository: bioimage-io/collection-bioimage-io
          ref: gh-pages
          path: bioimageio-gh-pages

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: See directory structure of the gh VM
        run: |
          java -version
          pwd
          ls -la
          echo --
          ls -la .. 
          echo --
          ls $GITHUB_WORKSPACE
