# This is a basic workflow to help you get started with Actions

name: CI - learning how to use gh-actions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab (github website)
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Check out another repository
      - uses: actions/checkout@v3
        with:
          repository: bioimage-io/collection-bioimage-io
          ref: gh-pages
          path: bioimageio-gh-pages

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: See directory structure of the gh VM
        run: |
          java -version
          pwd
          ls -la
          echo --
          ls -la bio*
          echo --
          ls $GITHUB_WORKSPACE | tee output.txt
          echo --
          echo ~
          echo --
          echo $HOME
      - name: Checking that previous output still there
        run: |
          ls
          cat output.txt


      - name: setup babashka
        uses: turtlequeue/setup-babashka@v1.5.0
        with:
          babashka-version: 1.0.168

      - name: run scripts for tests
        working-directory: ./java_CI_scripts
        run: |
          bb --version
          bb "(require '[collection-test] '[summaries-test]) (clojure.test/run-tests 'collection-test 'summaries-test)"
          echo -------
          bb -m core
          tree ../test_summaries -L 3 -h --du --dirsfirst # test-summaries folder should exist


